name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}:latest -f WebApplication1/Dockerfile .

    - name: Tag Docker image
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest
        docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

    - name: Pull Docker image from ECR
      run: |
        docker pull ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

    - name: Update Helm values.yaml with new image tag
      run: |
        sed -i "s|image: .*|image: ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG|g" helm/webapp/values.yaml
        cat helm/webapp/values.yaml

    - name: Check for untracked files
      run: |
        git status

    - name: Ignore untracked files
      run: |
        git add helm/webapp/values.yaml
        git commit -m "Update image tag to $IMAGE_TAG"
        git push
