name: Deploy to EKS using Argo CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 238393102293.dkr.ecr.ap-south-1.amazonaws.com/argocd-course-webapp-config
  ECR_REPOSITORY: argocd-course-webapp-config
  CLUSTER_NAME: cluster1
  ARGOCD_NAMESPACE: argocd

jobs:
  build_and_push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f ./WebApplication1/Dockerfile ]; then
            echo "Dockerfile not found!"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get current version
        id: get_version
        run: |
          if [ -f version.txt ]; then
            VERSION=$(cat version.txt)
            echo "Current version: $VERSION"
          else
            VERSION="dev0"
          fi
          VERSION_NUMBER=$(echo $VERSION | sed 's/dev//')
          NEW_VERSION_NUMBER=$((VERSION_NUMBER + 1))
          NEW_VERSION="dev$NEW_VERSION_NUMBER"
          echo $NEW_VERSION > version.txt
          echo "New version: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ env.version }} -f ./WebApplication1/Dockerfile .
          docker tag $ECR_REPOSITORY:${{ env.version }} $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.version }}

      - name: Push Docker image to Amazon ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.version }}
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.version }} $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Commit and push version file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add version.txt
          git commit -m "Increment version to ${{ env.version }}"
          git push

  deploy:
    name: Deploy to EKS using Argo CD
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Pull latest Docker image tag
        run: |
          LATEST_TAG=$(aws ecr describe-images --repository-name $ECR_REPOSITORY --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Update Helm values.yaml with new image
        run: |
          sed -i 's|repository:.*|repository: '"$ECR_REGISTRY/$ECR_REPOSITORY"'|' ./helm/webapp/values.yaml
          sed -i 's|tag:.*|tag: '"$LATEST_TAG"'|' ./helm/webapp/values.yaml

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin

      - name: Log in to Argo CD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

      - name: Sync Argo CD application
        run: |
          argocd app sync my-app
